spring.application.name=JWT

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=StarWars181222.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update
# Hibernate ddl auto (create, create-drop, validate, update)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

application.security.jwt.secret-key=McvbIkvPaVjhmKBwFdHDZxvFEAzgaJ8XJrc6BsVnKP19VUwAW7gZFMy62HhSI
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000